CMAKE_MINIMUM_REQUIRED(VERSION 2.8)

INCLUDE_DIRECTORIES(
  ${CMAKE_CURRENT_LIST_DIR}/src
  ${CMAKE_CURRENT_LIST_DIR}/../deps/libubox
  ${CMAKE_CURRENT_LIST_DIR}/../deps/uci
)

SET(SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/src/uci.c
)

LINK_DIRECTORIES("${CMAKE_CURRENT_SOURCE_DIR}/build/${BOARD_TYPE}/")

ADD_LIBRARY(luci SHARED ${SOURCES})
TARGET_LINK_LIBRARIES(luci uci ubox)
set_target_properties(luci PROPERTIES PREFIX "")
