CMAKE_MINIMUM_REQUIRED(VERSION 2.8)

INCLUDE_DIRECTORIES(
  ${CMAKE_CURRENT_LIST_DIR}/src
  ${CMAKE_CURRENT_LIST_DIR}/../deps/libubox
)

SET(SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/src/uloop.c
)

LINK_DIRECTORIES("${CMAKE_CURRENT_SOURCE_DIR}/build/${BOARD_TYPE}/")

ADD_LIBRARY(uloop SHARED ${SOURCES})
TARGET_LINK_LIBRARIES(uloop ubox lualib)
set_target_properties(uloop PROPERTIES PREFIX "")