#!/usr/bin/env sh

# 初始化 Node.lua 
# ======

# 这个脚本不会被打包到升级包中, 需在制作基本开发板固件(根文件系统)时
# 手动复制到开发板 `/etc/init.d/` 目录下

# tmpfs
# 将 /tmp 挂接为内存文件系统, /tmp 下文件经常变动且都为临时文件, 
# 所以用内存文件系统提高系统效率
mount tmpfs /tmp -t tmpfs

# 初始化网络接口
ifconfig eth0 192.168.77.113 netmask 255.255.255.0
ifconfig lo up
hostname hi3516a

telnetd

# 在开机时自动加载所有驱动程序
cd /ko
./load3516a -a -sensor imx178 -osmem 64
