cmake_minimum_required(VERSION 2.8)

set(BUILD_BLUETOOTH       OFF)
set(BUILD_MBEDTLS         ON)
set(BUILD_SDL             ON)
set(BUILD_SQLITE          ON)
set(BUILD_CAMERA          ON)
set(BUILD_MESSAGE         ON)
set(BUILD_TS              ON)
set(BUILD_MOSQUITTO       OFF)
set(BUILD_UBUS            OFF)
set(BUILD_UBOX            OFF)
set(BUILD_UCI             OFF)
