#!/bin/sh
# DT02 Gateway

# tmpfs
mount -t tmpfs -o size=16m tmpfs /tmp/

mkdir -p /tmp/lock
mkdir -p /tmp/log
mkdir -p /tmp/run
mkdir -p /tmp/sock

# network
lnode -l lci/mac

ifconfig lo up
ifconfig eth0 192.168.8.12 netmask 255.255.255.0
route add default gw 192.168.8.1

hostname dt02

telnetd &

# lpm
lpm start lci wotc gateway lpm
