#!/bin/sh
# DT02 Gateway

# tmpfs
mount -t tmpfs -o size=16m tmpfs /tmp/

mkdir -p /tmp/run
mkdir -p /tmp/lock
mkdir -p /tmp/log
mkdir -p /tmp/lock

# network
lnode -l lci/mac

ifconfig lo up
ifconfig eth0 192.168.8.12 netmask 255.255.255.0
route add default gw 192.168.8.1

hostname dt02

telnetd &

# nfs
# mount -t nfs -o nolock 192.168.1.38:/mnt/nfs /mnt/nfs

# lpm
lpm start lci wotc gateway lpm


# cd /mnt/dt02/node.lua/app/gateway/lua/lora/